Repository TUD-Patrec/annotation-tool, pull requests merged in 2023-03, with the labels that each got.

#9 Rename some GUI items
  annotation_tool/annotation/annotation_base.py
  annotation_tool/annotation/manual/tool_widget.py
  annotation_tool/dialogs/annotation_list.py
  annotation_tool/dialogs/load_annotation_dialog.py
  annotation_tool/dialogs/new_annotation_dialog.py
  annotation_tool/dialogs/settings_dialog.py
  annotation_tool/gui.py
  annotation_tool/playback.py
  annotation_tool/user_actions.py
  annotation_tool/utility/filehandler.py
Labels: refactor

#10 Remodel file cache and rename class attributes
  annotation_tool/__init__.py
  annotation_tool/annotation/annotation_base.py
  annotation_tool/annotation/retrieval/retrieval_backend/element.py
  annotation_tool/annotation/retrieval/retrieval_backend/loader.py
  annotation_tool/data_model/__init__.py
  annotation_tool/data_model/annotation.py
  annotation_tool/data_model/dataset.py
  annotation_tool/data_model/globalstate.py
  annotation_tool/data_model/project.py
  annotation_tool/data_model/sample.py
  annotation_tool/data_model/single_annotation.py
  annotation_tool/dialogs/annotation_dialog.py
  annotation_tool/dialogs/annotation_list.py
  annotation_tool/dialogs/dialog_manager.py
  annotation_tool/dialogs/load_annotation_dialog.py
  annotation_tool/dialogs/new_annotation_dialog.py
  annotation_tool/dialogs/settings_dialog.py
  annotation_tool/file_cache/__init__.py
  annotation_tool/file_cache/_file_cache.py
  annotation_tool/gui.py
  annotation_tool/main_controller.py
  annotation_tool/settings.py
  annotation_tool/utility/resources.py
  main.py
Labels: breaking-change

#11 Minor updates to the workflow files
  .github/workflows/lint.yml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/publish-to-testpypi.yml
  .github/workflows/release.yml
  .python-version
  pyproject.toml
Labels: ci-cd

#13 Add iconset for pyinstaller binaries
  sara.icns
Labels: other

#14 Add Windows icon and add Mac build targets to Makefile
  Makefile
  icons/sara.icns
  icons/sara.ico
Labels: other

#15 fix(local_files.py): fixed bugs in local_files-dialog
  annotation_tool/dialogs/local_files.py
  annotation_tool/file_cache/_file_cache.py
Labels: fix

#16 Add support for loading annotation-files
  annotation_tool/data_model/annotation.py
  annotation_tool/dialogs/dialog_manager.py
  annotation_tool/dialogs/import_annotation_dialog.py
  annotation_tool/gui.py
  annotation_tool/utility/filehandler.py
  sara.ico
Labels: feature

#17 Feat/UI changes
  annotation_tool/annotation/manual/main_widget.py
  annotation_tool/annotation/retrieval/retrieval_backend/filter_dialog.py
  annotation_tool/dialogs/annotation_dialog.py
  annotation_tool/dialogs/edit_datasets.py
  annotation_tool/playback.py
  annotation_tool/utility/resources.py
Labels: feature

#18 Fix repository not checked out on workflow call on 'lint.yml'
  .github/workflows/lint.yml
Labels: ci-cd

#21 Fix/video player
  annotation_tool/media/backend/controller.py
  annotation_tool/media/backend/player.py
  annotation_tool/media/backend/timer.py
  annotation_tool/media/backend/type_specific_player/mocap.py
Labels: fix
